"""Assembly guide generation"""

from datetime import datetime
from typing import Dict, List
from pathlib import Path


class AssemblyGuideGenerator:
    """Generates assembly README and documentation"""
    
    def __init__(self, layout_calculator):
        self.layout = layout_calculator
    
    def generate_readme(self, output_dir: Path) -> str:
        """Generate complete assembly README"""
        
        lines = []
        lines.append("# MyToolGrid Assembly Guide")
        lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f"**Total Dimensions:** {self.layout.total_length:.0f}mm × {self.layout.total_width:.0f}mm")
        lines.append(f"**Total Tiles Required:** {self.layout.get_total_tile_count()} tiles ({self.layout.get_unique_count()} unique geometries)\n")
        
        lines.append("## Files in This Package\n")
        lines.append("| Filename | Dimensions | Quantity | Type |")
        lines.append("|----------|-----------|----------|------|")
        
        for tile in self.layout.get_unique_tiles():
            dims = tile['dimensions']
            filename = f"tile_{dims[0]:.0f}x{dims[1]:.0f}_qty{tile['quantity']}.stl"
            lines.append(f"| {filename} | {dims[0]:.0f}×{dims[1]:.0f}mm | {tile['quantity']} | {tile['description']} |")
        
        lines.append(f"\n**Manufacturing Summary:**")
        lines.append(f"- Print/manufacture {self.layout.get_total_tile_count()} total tiles")
        lines.append(f"- {self.layout.get_unique_count()} unique STL files provided")
        lines.append(f"- All tiles are 6mm thick\n")
        
        lines.append(self.layout.generate_layout_diagram())
        
        lines.append("\n## Assembly Instructions\n")
        lines.append("### Step 1: Prepare Tiles")
        lines.append("- Manufacture all tiles according to filenames")
        lines.append("- Verify dimensions with calipers")
        lines.append("- Check that tabs and slots are clean and free of defects\n")
        
        lines.append("### Step 2: Assembly Order")
        lines.append("1. **Start with bottom-left:** Position first tile at origin")
        lines.append("2. **Build bottom row:** Add tiles moving right")
        lines.append("3. **Build upward:** Continue row by row from bottom to top")
        lines.append("4. **Complete assembly:** Add edge tiles last\n")
        
        lines.append("### Step 3: Interlocking System")
        lines.append("- **Tabs (male):** Located on TOP and RIGHT edges")
        lines.append("- **Slots (female):** Located on BOTTOM and LEFT edges")
        lines.append("- **Connection:** Each tile's right tabs fit into next tile's left slots")
        lines.append("- **Connection:** Each tile's top tabs fit into tile above's bottom slots\n")
        
        lines.append("### Step 4: Alignment Tips")
        lines.append("- Start from bottom-left corner")
        lines.append("- Work left-to-right, bottom-to-top")
        lines.append("- Press firmly to seat tabs in slots")
        lines.append("- Verify grid holes align across tiles\n")
        
        lines.append("## Troubleshooting\n")
        lines.append("**Tabs don't fit in slots:**")
        lines.append("- Check for printing artifacts or supports")
        lines.append("- Light sanding may be needed (0.2mm clearance designed in)\n")
        
        lines.append("**Tiles don't align:**")
        lines.append("- Verify manufacturing dimensions")
        lines.append("- Check assembly order\n")
        
        lines.append("**Gaps between tiles:**")
        lines.append("- Normal - slight gaps expected due to tolerances")
        lines.append("- Should not affect functionality\n")
        
        lines.append("---")
        lines.append("*Auto-generated by MyToolGrid Generator v1.0*")
        
        content = "\n".join(lines)
        
        # Write to file
        readme_path = output_dir / "ASSEMBLY_README.md"
        with open(readme_path, 'w') as f:
            f.write(content)
        
        return str(readme_path)
    
    def generate_layout_diagram_file(self, output_dir: Path) -> str:
        """Generate layout diagram as separate text file"""
        
        diagram = self.layout.generate_layout_diagram()
        
        diagram_path = output_dir / "layout_diagram.txt"
        with open(diagram_path, 'w') as f:
            f.write(diagram)
        
        return str(diagram_path)
